test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -32,6 +32,16 @@ jobs:
             echo "${{ secrets.FIREBASE_SECRET }}" | base64 --decode > todoapp-firebase-admin-sdk.json
         if: always()  
 
+      - name: Verify decoded Firebase secret file
+        run: |
+          if [ -f "todoapp-firebase-admin-sdk.json" ]; then
+            echo "Firebase secret file decoded successfully!"
+          else
+            echo "Error: Firebase secret file not found!"
+            exit 1  # Fail the workflow if the file is missing
+          fi
+
+
       - name: Change directory and run tests
         run: cd pkg/test/cmd && APP_ENV=test DB_PATH=test.db LOG_LEVEL=debug FIREBASE_ADMIN_SDK=todoapp-firebase-admin-sdk.json go run .
         if: always()
@@ -45,7 +55,7 @@ jobs:
           path: ${{ github.workspace }}/
 
       - name: Fail workflow on test failures (optional)
-        uses: styfle/cancel-workflow-action@0.8.0  # Or a similar action
+        uses: styfle/cancel-workflow-action@0.8.0 
         if: failure()  
         with:
           message: 'Tests failed. Fix the errors before merging.'
